apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  namespace: three-tier
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: gp2  # ✅ This enables AWS EBS dynamic provisioning
  resources:
    requests:
      storage: 1Gi

